const clients = [
  { name: 'Buyhive', type: '12 month engagement' },
  { name: 'Mogul', type: 'Active 12 month engagement' },
  { name: 'Bracketology', type: '12 month engagement' },
  { name: 'RXR', type: '12 month engagement' },
  { name: 'Remoteshare', type: 'Active' },
  { name: '1871', type: 'Active' },
  { name: 'UCFS', type: '12 month engagement' },
  { name: 'Keller Offers', type: '12 month engagement' },
  { name: 'Simple night', type: '12 month engagement' },
  { name: 'EVA', type: '12 month engagement' },
  { name: 'Kopfspringer', type: '12 month engagement' },
  { name: 'Kiwiwrite', type: 'Active' },
  { name: 'Maro', type: '12 month engagement' },
  { name: 'Farechild', type: '12 month engagement' },
  { name: 'Aurum', type: '12 month engagement' },
  { name: 'Big Shoulders Fund', type: '12 month engagement' },
  { name: 'Biograph', type: '12 month engagement' },
  { name: 'YOVI', type: '12 month engagement' },
  { name: 'Skoller', type: '12 month engagement' },
  { name: 'Shiny Registry', type: '12 month engagement' },
];